# Worksheet 1
## Exercise on Functions:

**Task - 1:**

Create a Python program that converts between different units of measurement.
*   The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
*   Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and return value.
*   Conversion Options:
1. Length:
- Convert meters (m) to feet (ft).
- Convert feet (ft) to meters (m).
2. Weight:
- Convert kilograms (kg) to pounds (lbs).
- Convert pounds (lbs) to kilograms (kg).
3. Volume:
- Convert liters (L) to gallons (gal).
- Convert gallons (gal) to liters (L).


In [1]:
def convert_length(value, from_unit, to_unit):
  """
  Purpose: To convert length from meters(m) to feet(ft) and vice versa

  Parameters:
  value (float): Value to convert
  from_unit (str): Unit to convert from ('m' or 'ft')
  to_unit (str): Unit to convert to ('m' or 'ft')

  Return value:
  float: converted value
  """
  units = {'m', 'ft'}
  if from_unit not in units or to_unit not in units:
    raise ValueError("Invalid units for length conversion. Use 'm' or 'ft'.")

  if from_unit == 'm' and to_unit == 'ft':
    return value * 3.28084
  elif from_unit == 'ft' and to_unit == 'm':
    return value / 3.28084
  else:
    raise ValueError("Invalid units for length conversion")

def convert_weight(value, from_unit, to_unit):
  """
  Purpose: To convert weight from kilograms(kg) to pounds(lbs) and vice versa

  Parameters:
  value (float): Value to convert
  from_unit (str): Unit to convert from ('kg' or 'lbs')
  to_unit (str): Unit to convert to ('kg' or 'lbs')

  Return value:
  float: converted value
  """
  units = {'kg', 'lbs'}
  if from_unit not in units or to_unit not in units:
    raise ValueError("Invalid units for weight conversion. Use 'kg' or 'lbs'.")

  if from_unit == 'kg' and to_unit == 'lbs':
    return value * 2.20462
  elif from_unit == 'lbs' and to_unit == 'kg':
    return value / 2.20462
  else:
    raise ValueError("Invalid units for weight conversion")

def convert_volume(value, from_unit, to_unit):
  """
  Purpose: To convert volume from liters(l) to gallons(gal) and vice versa

  Parameters:
  value (float): Value to convert
  from_unit (str): Unit to convert from ('l' or 'gal')
  to_unit (str): Unit to convert to ('l' or 'gal')

  Return value:
  float: converted value
  """
  units = {'l', 'gal'}
  if from_unit not in units or to_unit not in units:
    raise ValueError("Invalid units for volume conversion. Use 'l' or 'gal'.")

  if from_unit == 'l' and to_unit == 'gal':
    return value * 0.264172
  elif from_unit == 'gal' and to_unit == '':
    return value / 0.264172
  else:
    raise ValueError("Invalid units for volume conversion")

def main():
  """
  Main function to run the program to convert between different units of measurement
  """
  while True:
    print("\nList of Types of Conversions:")
    print("1. Length (m/ft)")
    print("2. Weight (kg/lbs)")
    print("3. Volume (l/gal)")

    try:
      choice = int(input("\nEnter your choice or 4 to exit: "))

      if choice == 4:
        print("Exiting the program.")
        break

      if choice not in [1, 2, 3]:
        raise ValueError("Invalid choice. Please select a valid conversion type.")

      while True:
        try:
          value = float(input("Enter the value to be converted: "))
          if value <= 0:
            print("Error: Please enter a positive number.")
            continue
          break
        except ValueError:
          print("Error: Please enter a valid number.")

      if choice == 1:
        from_unit = input("Enter the unit to convert from (m or ft): ").lower()
        to_unit = input("Enter the unit to convert to (m or ft): ").lower()
        result = convert_length(value, from_unit, to_unit)

      elif choice == 2:
        from_unit = input("Enter the unit to convert from (kg or lbs): ").lower()
        to_unit = input("Enter the unit to convert to (kg or lbs): ").lower()
        result = convert_weight(value, from_unit, to_unit)

      elif choice == 3:
        from_unit = input("Enter the unit to convert from (l or gal): ").lower()
        to_unit = input("Enter the unit to convert to (l or gal): ").lower()
        result = convert_volume(value, from_unit, to_unit)

      print(f"\nResult: {value} {from_unit} is equal to {result:.2f} {to_unit}.")
    except ValueError as e:
      print(f"Error: {e}")
    except Exception as e:
      print(f"Unexpected error: {e}")

main()


List of Types of Conversions:
1. Length (m/ft)
2. Weight (kg/lbs)
3. Volume (l/gal)

Enter your choice or 4 to exit: 2
Enter the value to be converted: 20
Enter the unit to convert from (kg or lbs): kg
Enter the unit to convert to (kg or lbs): 2
Error: Invalid units for weight conversion. Use 'kg' or 'lbs'.

List of Types of Conversions:
1. Length (m/ft)
2. Weight (kg/lbs)
3. Volume (l/gal)

Enter your choice or 4 to exit: 3
Enter the value to be converted: 100
Enter the unit to convert from (l or gal): l
Enter the unit to convert to (l or gal): gal

Result: 100.0 l is equal to 26.42 gal.

List of Types of Conversions:
1. Length (m/ft)
2. Weight (kg/lbs)
3. Volume (l/gal)

Enter your choice or 4 to exit: 4
Exiting the program.


**Task - 2:**

Create a Python program that performs various mathematical operations on a list of numbers.
*   The program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum of the numbers)
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
*   Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, minimum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [2]:
def add(numbers):
  """
  Purpose: To calculate the sum of a list of numbers

  Parameters:
  numbers: A list of numeric values

  Return value:
  float: Sum of the numbers in the list
  """
  return sum(numbers)

def average(numbers):
  """
  Purpose: To calculate the average(mean) of a list of numbers

  Parameters:
  numbers: A list of numeric values

  Return value:
  float: Average of the numbers in the list
  """
  return sum(numbers) / len(numbers)

def maximum(numbers):
  """
  Purpose: To find the maximum number in a list

  Parameters:
  numbers: A list of numeric values

  Return value:
  float: Maximum number in the list
  """
  return max(numbers)

def minimum(numbers):
  """
  Purpose: To find the minimum number in a list

  Parameters:
  numbers: A list of numeric values

  Return value:
  float: Minimum number in the list
  """
  return min(numbers)

def main():
  """
  Main function that prompts the user to select an operation and input a list of numbers.
  Performs the selected operation and displays the result.
  Handles errors for invalid inputs and empty lists.
  """
  while True:
    print("\nList of Operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
      choice = int(input("Enter your choice or 5 to exit: "))

      if choice == 5:
        print("Exiting the program.")
        break

      if choice not in [1, 2, 3, 4]:
        print("Invalid choice. Please select a valid option.")
        continue
      numbers_input = input("Enter numbers separated by spaces: ")
      numbers_list = [float(num) for num in numbers_input.split()]

      if not numbers_list:
        print("Error: The list of numbers cannot be empty.")
        continue

      if choice == 1:
        result = add(numbers_list)
        print(f"\nSum: {result}")
      elif choice == 2:
        result = average(numbers_list)
        print(f"\nAverage: {result}")
      elif choice == 3:
        result = maximum(numbers_list)
        print(f"\nMaximum: {result}")
      elif choice == 4:
        result = minimum(numbers_list)
        print(f"\nMinimum: {result}")

    except ValueError:
      print("Error: Please enter valid numeric values.")
    except Exception as e:
      print(f"Unexpected error: {e}")

main()


List of Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice or 5 to exit: 1
Enter numbers separated by spaces: 3

Sum: 3.0

List of Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice or 5 to exit: 2
Enter numbers separated by spaces: 6

Average: 6.0

List of Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice or 5 to exit: 2
Enter numbers separated by spaces: 2 2'
Error: Please enter valid numeric values.

List of Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice or 5 to exit: 1
Enter numbers separated by spaces: 2 2

Sum: 4.0

List of Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice or 5 to exit: 5
Exiting the program.


## Exercise on List Manipulation:

1. Extract Every Other Element:

  Write a Python function that extracts every other element from a list, starting from the first element.

  Requirements:
- Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
- Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].


In [3]:
def extract_every_other(lst):
  return lst[::2]

input_list = [1, 2, 3, 4, 5, 6]
new_list = extract_every_other(input_list)
print(f"Every other element of the list:\n{new_list}")

Every other element of the list:
[1, 3, 5]


2. Slice a Sublist:

  Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

  Requirements:
- Define a function get sublist(lst, start, end) that takes a list lst, a starting index start, and an ending index end as input and returns the sublist from start to end (inclusive).
- Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should be [3, 4, 5].

In [4]:
def get_sublist(lst, start, end):
  return lst[start:end+1]

input_list = [1, 2, 3, 4, 5, 6]
sublist = get_sublist(input_list, 2, 4)
print(f"Sublist starting from index 2 to index 4:\n{sublist}")

Sublist starting from index 2 to index 4:
[3, 4, 5]


3. Reverse a List Using Slicing:

  Write a Python function that reverses a list using slicing.

  Requirements:
- Define a function reverse list(lst) that takes a list lst and returns a reversed list using slicing.
- Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [5]:
def reverse_list(lst):
  return lst[::-1]

input_list = [1, 2, 3, 4, 5]
reversed = reverse_list(input_list)
print(f"Reversed List:\n{reversed}")

Reversed List:
[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

  Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

  Requirements:
- Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
- Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [6]:
def remove_first_last(lst):
  return lst[1:-1]

input_list = [1, 2, 3, 4, 5]
sublist = remove_first_last(input_list)
print(f"Modified List:\n{sublist}")

Modified List:
[2, 3, 4]


5. Get the First n Elements:

  Write a Python function that extracts the first n elements from a list.

  Requirements:
- Define a function get first n(lst, n) that takes a list lst and an integer n as input and returns the first n elements of the list using slicing.
- Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [7]:
def get_first_n(lst, n):
  return lst[:n]

input_list = [1, 2, 3, 4, 5]
n = 3
sublist = get_first_n(input_list, n)
print(f"First {n} elements:\n{sublist}")

First 3 elements:
[1, 2, 3]


6. Extract Elements from the End:

  Write a Python function that extracts the last n elements of a list using slicing.

  Requirements:
- Define a function get last n(lst, n) that takes a list lst and an integer n as input and returns the last n elements of the list.
- Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [8]:
def get_last_n(lst, n):
  return lst[-n:]

input_list = [1, 2, 3, 4, 5]
n = 2
sublist = get_last_n(input_list, n)
print(f"Last {n} elements:\n{sublist}")

Last 2 elements:
[4, 5]


7. Extract Elements in Reverse Order:

  Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

  Requirements:
- Define a function reverse skip(lst) that takes a list lst and returns a new list containing every second element starting from the second-to-last, moving backward.
- Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [9]:
def reverse_skip(lst):
  return lst[-2::-2]

input_list = [1, 2, 3, 4, 5, 6]
sublist = reverse_skip(input_list)
print(f"Every other element in reverse order:\n{sublist}")

Every other element in reverse order:
[5, 3, 1]


## Exercise on Nested List:

1. Flatten a Nested List:

  Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

  Requirements:
- Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list.
- Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [10]:
def flatten(lst):
  flattened_list = []
  for sublist in lst:
    for item in sublist:
      flattened_list.append(item)
  return flattened_list

input_list = [[1, 2], [3, 4], [5]]
single_list = flatten(input_list)
print(f"Flattened List:\n{single_list}")

Flattened List:
[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:

  Write a Python function that extracts a specific element from a nested list given its indices.

  Requirements:
- Define a function access nested element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position.
- Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1, 2], the output should be 6.

In [11]:
def access_nested_element(lst, indices):
  element = lst
  for index in indices:
    element = element[index]
  return element

input_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
element = access_nested_element(input_list, indices)
print(f"Element at index[1,2]: {element}")

Element at index[1,2]: 6


3. Sum of All Elements in a Nested List:

  Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

  Requirements:
- Define a function sum nested(lst) that takes a nested list lst and returns the sum of all the elements.
- Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [12]:
def sum_nested(lst):
  total = 0
  for item in lst:
    if type(item) == list:
      total += sum_nested(item)
    else:
      total += item
  return total

input_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(input_list)
print(f"Sum of all elements: {result}")

Sum of all elements: 21


4. Remove Specific Element from a Nested List:
  
  Write a Python function that removes all occurrences of a specific element from a nested list.

  Requirements:
- Define a function remove element(lst, elem) that removes elem from lst and returns the modified list.
- Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should be [[1], [3], [4, 5]].

In [13]:
def remove_element(lst, elem):
  result = []
  for item in lst:
    if type(item) == list:
      new_sublist = remove_element(item, elem)
      if new_sublist:
        result.append(new_sublist)
    elif item != elem:
      result.append(item)
  return result

input_list = [[1, 2], [3, 2], [4, 5]]
element = 2
result = remove_element(input_list, element)
print(f"Modified list:\n{result}")

Modified list:
[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:

  Write a Python function that finds the maximum element in a nested list (regardless of depth).

  Requirements:
- Define a function find max(lst) that takes a nested list lst and returns the maximum element.
- Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [14]:
def find_max(lst):
  max_val = float('-inf')
  for item in lst:
    if type(item) == list:
      max_val = max(max_val, find_max(item))
    else:
      max_val = max(max_val, item)
  return max_val

input_list = [[1, 2], [3, [4, 5]], 6]
max_value = find_max(input_list)
print(f"Maximum element: {max_value}")

Maximum element: 6


6. Count Occurrences of an Element in a Nested List:

  Write a Python function that counts how many times a specific element appears in a nested list.

  Requirements:
- Define a function count occurrences(lst, elem) that counts the occurrences of elem in the nested list lst.
- Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should be 3.

In [15]:
def count_occurrences(lst, elem):
  count = 0
  for item in lst:
    if type(item) == list:
      count += count_occurrences(item, elem)
    elif item == elem:
      count += 1
  return count

input_list = [[1, 2], [2, 3], [2, 4]]
element = 2
result = count_occurrences(input_list, element)
print(f"Element {element} occurs {result} times")

Element 2 occurs 3 times


7. Flatten a List of Lists of Lists:

  Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

  Requirements:
- Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single flattened list.
- Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be [1, 2, 3, 4, 5, 6, 7, 8].

In [16]:
def deep_flatten(lst):
  flattened_list = []
  for item in lst:
    if type(item) == list:
      flattened_list.extend(deep_flatten(item))
    else:
      flattened_list.append(item)
  return flattened_list

input_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
flattened_list = deep_flatten(input_list)
print(f"Flattened List:\n{flattened_list}")

Flattened List:
[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:

  Write a Python function that calculates the average of all elements in a nested list.

  Requirements:
- Define a function average nested(lst) that takes a nested list lst and returns the average of all the elements.
- Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [17]:
def average_nested(lst):
  def deep_flatten(lst):
    flattened_list = []
    for item in lst:
      if type(item) == list:
        flattened_list.extend(deep_flatten(item))
      else:
        flattened_list.append(item)
    return flattened_list

  flattened_list = deep_flatten(lst)
  if flattened_list:
    return sum(flattened_list) / len(flattened_list)
  else:
    return 0

input_list = [[1, 2], [3, 4], [5, 6]]
average = average_nested(input_list)
print(f"Average of elements in the list: {average}")

Average of elements in the list: 3.5


## Basic Vector and Matrix Operation with Numpy
### Problem - 1: Array Creation:


In [18]:
import numpy as np

1. Initialize an empty array with size 2X2.

In [19]:
empty_arr = np.empty((2,2))
print(f"Empty array:\n{empty_arr}")

Empty array:
[[1.45033939e-316 0.00000000e+000]
 [6.64802899e-310 6.64802900e-310]]


2. Initialize an all one array with size 4X2.

In [20]:
ones_arr = np.ones((4,2))
print(f"All one array:\n{ones_arr}")

All one array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [21]:
arr = np.full((3,2), 5, dtype=int)
print(arr)

[[5 5]
 [5 5]
 [5 5]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [22]:
print(np.zeros_like(arr))

[[0 0]
 [0 0]
 [0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [23]:
print(np.ones_like(arr))

[[1 1]
 [1 1]
 [1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [24]:
new_list = [1,2,3,4]
new_arr = np.array(new_list)
print(f"Array: {new_arr}")
print(f"Type: {type(new_arr)}")

Array: [1 2 3 4]
Type: <class 'numpy.ndarray'>


### Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [25]:
print(f"Array with values from 10 to 49:\n{np.arange(10, 49)}")

Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


2. Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}

In [26]:
array = np.arange(9)
matrix = np.reshape(array, (3,3))
print(f"3X3 matrix with values from 0 to 8:\n{matrix}")

3X3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [27]:
identity = np.eye(3, dtype=int)
print(f"3X3 identity matrix:\n{identity}")

3X3 identity matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [28]:
random_arr = np.random.random(30)
print(f"Random array of size 30:\n{random_arr}")
mean = np.mean(random_arr)
print(f"\nMean: {mean}")

Random array of size 30:
[0.39949519 0.31159854 0.35317778 0.89591297 0.69045604 0.53126065
 0.55610028 0.43908861 0.5436755  0.9989511  0.54201463 0.28964935
 0.27377494 0.60386055 0.82096663 0.49219753 0.22962413 0.33688153
 0.42474299 0.28887202 0.30718488 0.42104743 0.47071197 0.15275392
 0.27595535 0.74392038 0.33997082 0.83094558 0.47692056 0.77491602]

Mean: 0.49388759534708987


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [29]:
random_arr1 = np.random.random((10, 10))
print(f"10X10 array with random values:\n{random_arr1}")
print(f"\nMinimum value: {np.min(random_arr1)}")
print(f"\nMaximum value: {np.max(random_arr1)}")

10X10 array with random values:
[[0.13735062 0.1153422  0.32456023 0.73792686 0.89588937 0.41064464
  0.34429783 0.0286805  0.90181178 0.47747069]
 [0.26324677 0.94296678 0.33574979 0.17157106 0.26996381 0.10526079
  0.46507035 0.81473365 0.63526203 0.67560809]
 [0.12402466 0.08784568 0.83997779 0.53037975 0.65031406 0.24115928
  0.12143685 0.67658631 0.64039048 0.71853626]
 [0.47012684 0.26572239 0.35662523 0.71523532 0.40126555 0.33822154
  0.68719995 0.24516946 0.14620884 0.94981664]
 [0.40013708 0.19770923 0.39058685 0.21402857 0.43505913 0.28757763
  0.42289806 0.81252868 0.09901076 0.4409404 ]
 [0.49781976 0.24582633 0.13706901 0.1267158  0.38967976 0.22802763
  0.16564474 0.39775866 0.12189378 0.9294239 ]
 [0.8226325  0.01945751 0.46942147 0.28763326 0.57113206 0.24875362
  0.45655432 0.42828857 0.06129083 0.19368675]
 [0.50682709 0.30018646 0.41192135 0.03440261 0.92643656 0.31230941
  0.80451956 0.91628729 0.73486899 0.40924151]
 [0.75153792 0.21453197 0.98175585 0.21636259 0.

6. Create a zero array of size 10 and replace 5th element with 1.

In [30]:
zeros_arr = np.zeros(10, dtype=int)
zeros_arr[4] = 1
print(zeros_arr)

[0 0 0 0 1 0 0 0 0 0]


7. Reverse an array arr = [1,2,0,0,4,0].

In [31]:
arr = np.array([1,2,0,0,4,0])
reversed = arr[::-1]
print(f"Reversed array: {reversed}")

Reversed array: [0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [32]:
array = np.ones((7, 7), dtype=int)
array[1:-1, 1:-1]=0
print(f"2d array with 1 on border and 0 inside:\n{array}")

2d array with 1 on border and 0 inside:
[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [33]:
array = np.zeros((8, 8), dtype=int)
array[1::2, ::2]=1
array[::2, 1::2]=1
print(f"A checkerboard pattern 8x8 matrix:\n{array}")

A checkerboard pattern 8x8 matrix:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:


1. Add the two array.

In [34]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("Addition:")
add_xy = np.add(x, y)
print(add_xy)
print("")
add_vw = np.add(v, w)
print(add_vw)

Addition:
[[ 6  8]
 [10 13]]

[20 22]


2. Subtract the two array.

In [35]:
print("Subtraction")
subtract_xy = np.subtract(x, y)
print(subtract_xy)
print("")
subtract_vw = np.subtract(v, w)
print(subtract_vw)

Subtraction
[[-4 -4]
 [-4 -3]]

[-2 -2]


3. Multiply the array with any integers of your choice.

In [36]:
print("Multipliplication:")
multiply1 = np.dot(x, 2)
print(multiply1)
print("")
multiply2 = np.dot(y, 3)
print(multiply2)

Multipliplication:
[[ 2  4]
 [ 6 10]]

[[15 18]
 [21 24]]


4. Find the square of each element of the array.

In [37]:
print("Square of each element:")
squared_arrx = x ** 2
print(squared_arrx)
print("")
squared_arrv = v ** 2
print(squared_arrv)

Square of each element:
[[ 1  4]
 [ 9 25]]

[ 81 100]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [38]:
print("Dot Products:")
dot_prod_vw = np.dot(v, w)
print("\nv(and)w:", dot_prod_vw)
dot_prod_xv = np.dot(x, v)
print("\nx(and)v:", dot_prod_xv)
dot_prod_xy = np.dot(x, y)
print("\nx(and)y:", dot_prod_xy)

Dot Products:

v(and)w: 219

x(and)v: [29 77]

x(and)y: [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.

In [39]:
print("Concatenating x(and)y along row:")
concatenate_row = np.concatenate((x, y), axis=0)
print(concatenate_row)

print("\nConcatenating v(and)w along column:")
concatenate_column = np.concatenate_column = np.vstack((v, w)).T
print(concatenate_column)

Concatenating x(and)y along row:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenating v(and)w along column:
[[ 9 11]
 [10 12]]


### Problem - 4: Matrix Operations:
- For the following arrays:

  A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

  Prove following with Numpy:
  1. Prove A.A−1 = I.
  2. Prove AB ̸= BA.
  3. Prove(AB)T =BTAT.

In [41]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

from numpy import linalg

inverse_A = np.linalg.inv(A)
result1 = np.dot(A, inverse_A)
print(f"Result of A.A−1:\n{np.round(result1)}")

prod_AB = np.dot(A, B)
prod_BA = np.dot(B, A)

check = np.array_equal(A, B)
print("\n")
if check == True:
  print("AB = BA")
else:
  print("AB != BA")

transpose_A = np.transpose(A)
transpose_B = np.transpose(B)

prod_BTAT = np.dot(transpose_B, transpose_A)
transpose_AB = np.transpose(prod_AB)

check1 = np.array_equal(transpose_AB, prod_BTAT)
print("\n")
if check1 == True:
  print("(AB)T = BT.AT")
else:
  print("(AB)T != BT.AT")

Result of A.A−1:
[[1. 0.]
 [0. 1.]]


AB != BA


(AB)T = BT.AT


- Solve the following system of Linear equation using Inverse Methods.

  2x − 3y + z = −1

  x − y + 2z = −3

  3x + y − z = 9

  {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [42]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

print("Coefficient matrix A:")
print(A)
print("\nConstant matrix B:")
print(B)

# find the determinant of A
det_A = np.linalg.det(A)

# find the adjugate matrix of A
cofactor_matrix = np.zeros_like(A, dtype=float)

# find the cofactor matrix using a loop
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        minor_matrix = np.delete(np.delete(A, i, axis=0), j, axis=1)
        cofactor_matrix[i, j] = ((-1) ** (i + j)) * np.linalg.det(minor_matrix)

adjugate_matrix = cofactor_matrix.T

# find the inverse of A
A_inv = adjugate_matrix / det_A

X = np.dot(A_inv, B)

print("\nSolution vector X using inverse method:")
print(X)

Coefficient matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Constant matrix B:
[-1 -3  9]

Solution vector X using inverse method:
[ 2.  1. -2.]


- Now: solve the above equation using np.linalg.inv function. {Explore more about ”linalg” func- tion of Numpy}

In [43]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

inv_A = np.linalg.inv(A)
X = np.dot(inv_A, B)
print("Solution vector X using np.linalg.inv function:")
print(X)

Solution vector X using np.linalg.inv function:
[ 2.  1. -2.]


### Experiment: How Fast is Numpy?

1. Element-wise Addition:
- Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
- Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.


In [44]:
import time

list1 = [i for i in range(1,1000001)]
list2 = [i for i in range(1000001,2000001)]

start_time = time.time()
result_time = [a+b for a,b in zip(list1, list2)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken for element-wise addition: {list_time} seconds")

array1 = np.array(list1)
array2 = np.array(list2)

start_time = time.time()
result_array = array1 + array2
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken for element-wise addition using Numpy arrays: {array_time} seconds")

Time taken for element-wise addition: 0.1100456714630127 seconds
Time taken for element-wise addition using Numpy arrays: 0.0072324275970458984 seconds


2. Element-wise Multiplication
- Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000. Measure and Print the time taken for this operation.
- Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [45]:
list1 = [i for i in range(1,1000001)]
list2 = [i for i in range(1000001,2000001)]

start_time = time.time()
result_time = [a*b for a,b in zip(list1, list2)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken for element-wise multiplication: {list_time} seconds")

array1 = np.array(list1)
array2 = np.array(list2)

start_time = time.time()
result_array = array1 * array2
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken for element-wise multiplication using Numpy arrays: {array_time} seconds")

Time taken for element-wise multiplication: 0.13102102279663086 seconds
Time taken for element-wise multiplication using Numpy arrays: 0.00617218017578125 seconds


3. Dot Product
- Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
- Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [46]:
list1 = [i for i in range(1,1000001)]
list2 = [i for i in range(1000001,2000001)]

start_time = time.time()
result_time = [a*b for a,b in zip(list1, list2)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken for computing the dot product: {list_time} seconds")

array1 = np.array(list1)
array2 = np.array(list2)

start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken for computing the dot product using Numpy arrays: {array_time} seconds")

Time taken for computing the dot product: 0.11831045150756836 seconds
Time taken for computing the dot product using Numpy arrays: 0.0023894309997558594 seconds


4. Matrix Multiplication
- Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea- sure and print the time taken for this operation.
- Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [ ]:
N=1000

matrix1 = [[i + j for j in range(N)] for i in range(N)]
matrix2 = [[i - j for j in range(N)] for i in range(N)]

def matrix_multiply(A,B):
  result = [[0] *N for _ in range(N)]
  for i in range(N):
    for j in range(N):
      for k in range(N):
        result[i][j] += A[i][k] * B[k][j]
  return result

start_time = time.time()
result = matrix_multiply(matrix1, matrix2)
end_time = time.time()
execute_time = end_time - start_time
print(f"Time taken for matrix multiplication: {execute_time} seconds")

array1 = np.array(matrix1)
array2 = np.array(matrix2)

start_time = time.time()
result_numpy = np.dot(array1, array2)
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken for matrix multiplication using Numpy arrays: {numpy_time:.6f} seconds")